# Generated by Django 3.1.4 on 2020-12-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
