# Generated by Django 3.1.4 on 2020-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201226_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие сд карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем сд карты'),
        ),
    ]
