# Generated by Django 3.1.4 on 2021-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210105_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке')], default='new', max_length=100, verbose_name='Статус'),
        ),
    ]
