# Generated by Django 3.1.4 on 2021-01-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210109_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_customer', to='mainapp.Order', verbose_name='заказы покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('self', 'Самовывоз')], default='self', max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Заказ выполнен'), ('in_progress', 'Заказ в обработке'), ('new', 'Новый заказ'), ('ready', 'Заказ готов')], default='new', max_length=100, verbose_name='Статус'),
        ),
    ]
