# Generated by Django 3.1.4 on 2021-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210109_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='mainapp.Order', verbose_name='заказы покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('in_progress', 'Заказ в обработке'), ('new', 'Новый заказ')], default='new', max_length=100, verbose_name='Статус'),
        ),
    ]
