# Generated by Django 3.1.4 on 2021-01-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210110_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('self', 'Самовывоз')], default='self', max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Заказ в обработке'), ('ready', 'Заказ готов'), ('new', 'Новый заказ'), ('completed', 'Заказ выполнен')], default='new', max_length=100, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название спецификации')),
                ('slug', models.SlugField(unique=True)),
                ('required', models.BooleanField(verbose_name='Обязательно для заполнение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_specifications', to='mainapp.category', verbose_name='Категория')),
            ],
        ),
    ]
